### ISSUE TITLE
I have problems getting the library to work.

### ISSUE THREAD

**Issue by semrwj** [Rynstick/LBS#2]
I did it as described on the website and tried everything but got no output from getRandomNumber. TraceViewer displays: "Adding module failed: '/global_modules/LBS_V_0_0_77.js'
error='ResultCode: 0x80000c Error: CF_R_EXISTS Description: The component reported a general error (File: D:\agent\_work\48\source\CCScriptComp\ScriptContext.cpp, Func: CCScriptFW::CScriptContext::DoCommand::<lambda_3>::operator ())'". I have uploaded a demo project, can you take a look at it? 

Thanks in advance

[Testprojekt Database Connection_20231010_0853.zip](https://github.com/Rynstick/LBS/files/12853805/Testprojekt.Database.Connection_20231010_0853.zip)

**Comment by Rynstick** [comment]
will do ! ill let you know

**Comment by semrwj** [comment]
Sorry for the inconvenience, but there is nothing wrong with your library. It seems that there is a bug in Unified Runtime V18 Update 2 that causes the entire Task Scheduler to suddenly stop running under unknown circumstances.  After reinstalling on a fresh system, the Task Scheduler works again and I can successfully admire random numbers in the Trace Viewer. The above error is still there, but does not seem to affect the functionality.

Thank you and good day

**Comment by semrwj** [comment]
Sorry for the inconvenience, but there is nothing wrong with your library. It seems that there is a bug in Unified Runtime V18 Update 2 that causes the entire Task Scheduler to suddenly stop running under unknown circumstances.  After reinstalling on a fresh system, the Task Scheduler works again and I can successfully admire random numbers in the Trace Viewer. The above error is still there, but does not seem to affect the functionality.

Thank you and good day

**Comment by Rynstick** [comment]
great to hear ! v18 update 2 is still very early so i would not build anything serious on it keep it on 18 v0 or v1
